lxqt/lxqt-runner

dialog.ui
=> Sets the command list to use alternating row colors

providers.cpp
Fixes lxde/lxqt#15 similary as @eerden in lxde/lxqt-runner#6, but only as fallback mechanism...
=> fallback for executing scripts w/o #!

commanditemmodel.cpp, providers.cpp, providers.h
lxqt-session's lxqt-leave provides them as well.
Fixes lxde/lxqt#476.
=> Remove the provider for power actions

dialog.cpp
as done in lxde/liblxqt/pull/36
=> remove KF5/ prefix from include

translations/lxqt-runner_el.ts
=> Remove country variant from language code

commanditemmodel.cpp, providers.cpp, providers.h
Please, test if I didn't overook something and the filtering is correct ...
closes lxde/lxqt#478
=> Filtering of custom command items in case equivalent .desktop entry shown

dialog.cpp
=> Fix layout and focus to get history items right

commanditemmodel.cpp, commanditemmodel.h, configuredialog/configuredialog.cpp, configuredialog/configuredialog.ui, dialog.cpp
Also add posibility to configure position of history items (first/last)
=> runner: Sort history items by relevance

CMakeLists.txt, providers.cpp, providers.h
=> Math: Use libmuparser for math evaluation

CMakeLists.txt
=> Use the new MenuCache configuration CMake module

providers.cpp, providers.h
=> MathItem: Honor system locale

commanditemmodel.cpp, commanditemmodel.h, configuredialog/configuredialog.cpp, configuredialog/configuredialog.ui, dialog.cpp
=> History configurable

configuredialog/configuredialog.cpp, configuredialog/configuredialog.ui, dialog.cpp, dialog.ui, mylistview.h
=> ui: Add option to show particular count of items

CMakeLists.txt, providers.cpp
needs lxde/menu-cache#15
fixes lxde/lxqt#1278
=> AppLinkItem: Make genericName searchable

CMakeLists.txt, autostart/CMakeLists.txt, translations/CMakeLists.txt
=> Set cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)

providers.cpp
..and check for possible ArgSep() and DecSep() conflict.
=> MathItem: Use documented API of muparser

providers.cpp
=> Copy calculation result to clipboard

CMakeLists.txt, commanditemmodel.cpp, commanditemmodel.h, configuredialog/configuredialog.cpp, dialog.cpp, dialog.h, providers.cpp, providers.h
Some changes needed to let things work
=> Move to Qt5 signal/slot syntax

dialog.cpp
Because they could cause crashes (on hiding the dialog).
=> Don't call `KX11Extras` methods on Wayland

dialog.cpp
Closes https://github.com/lxqt/lxqt-runner/issues/296
=> Guarantee case-insensitive filtering

configuredialog/configuredialog.cpp, dialog.cpp, dialog.h
Closes https://github.com/lxqt/lxqt-runner/issues/300
=> Handle Wayland screens by using their names

configuredialog/configuredialog.cpp, configuredialog/configuredialog.ui
Also, disabled the shortcut widget on Wayland.
=> Added tooltips on Wayland
