lxqt/lxqt-runner

- dialog.cpp
We ship the icons with all themes (qss). Only a cosmic ray would make that
fail. We should not set an "fallback" in the code. That kind of
interactions are known to be undefined.
Closes lxde/lxqt#754
> Fixes Action button missing (menu) icon

- AUTHORS
- commanditemmodel.h
- yamlparser.cpp
- yamlparser.h
* GPL2 removed from AUTHORS, all files are LGPL
* slash removed in commanditemmodel.h - breaks debians licensecheck
* yamlparser.* LGPL2.1 Author Christian - must be enough for the moment
we must discuss and solve the license things asap, right now i need
some valid license headers for debian - this doesn't change any
copyright things for Christian, as he will held all rights on his own
code
> some license fixes

- dialog.ui
Auto filling background is needed for "System" a.k.a. "No Theme"
ref. lxde/lxqt#892
> dialog: Fill background

- main.cpp
Use LXQt::SingleApplication to be able to activate/show window of the running daemon
This is another possibility for showing the runner by executing the `lxqt-runner` (first instance is running as a daemon and every next invocation just show the daemon's window)
This needs lxde/liblxqt#76
closes lxde/lxqt#920
> main: Add activation by running second instance

- dialog.cpp
`showHide` doesn't work for this because when it gets called the window
is no longer the active window, so instead of hiding it, it forces it
back as the active window.
> Properly hide the runner when it loses focus

- dialog.cpp
- dialog.h
If runner is shown and virtual desktop is changed, show/activate the runner there.
Addressing also the problem depicted by @pmattern in #43:
> ...the GUI of lxqt-runner is disappearing right after invoking here most of the time and in an unpredictable way (failed to figure out when this happens so far).
> The problem appears when the runner GUI was closed by hitting Esc without taking any action. E. g. start an LXQt session, launch the GUI by hitting Alt+F2 → everything fine. Close the GUI by hitting Esc without taking any action, open it again → disappears at once and continues to behave like this until the runner daemon is restarted.
> runner: Follow virtual desktop switching

- providers.cpp
The wrong placement of the test is breaking compilations that do not use
muParser library
> - Fix endif placement when test for MATH library.

- providers.cpp
pkg-main/lxqt-runner/snapshot/providers.cpp:813:47: warning: extra ‘;’ [-Wpedantic]
Q_COREAPP_STARTUP_FUNCTION(muParserInitLocale);
> Fix pedantic warning

- dialog.cpp
- providers.cpp
..as there is no need to use the XdgIcon version (and there are
problems with caching in the XdgIcon::fromTheme).
ref. lxde/lxqt#1444
> Use the QIcon::fromTheme()

- CMakeLists.txt
Stop using LXQT_MINIMUM_VERSION as the minimum required version for
lxqt-globalkeys.
lxqt-globalkeys is a lxqt-globalkeys-ui dependency.
Issue description: https://github.com/lxqt/lxqt-panel/issues/1022
> cmake: Enhance lxqt-globalkeys minimum required version

- dialog.cpp
- dialog.h
This is exactly like https://github.com/lxqt/lxqt-panel/pull/1173 but more urgent because the freeze-like behavior is more tangible with Runner. It starts searching (filtering) only when the user stops typing.
Also, updated the syntax of some connections.
> Smoother search

- dialog.cpp
Fixes https://github.com/lxqt/lxqt-runner/issues/169
Also:
1. Added `Home` and `End` to keys; and
2. Reduced the timer's timeout to 250ms (350 was Alf's indirect suggestion).
> Don't change current row of dropdown list if it already exists

- dialog.cpp
- providers.cpp
Because, unlike a search, it might be used later (@stefonarch's idea).
Closes https://github.com/lxqt/lxqt-runner/issues/178
> Select math result on showing lxqt-runner

- CMakeLists.txt
Just a typo.
Closes https://github.com/lxqt/lxqt/issues/1975.
> Fix a MenuCache typo FTBFS

- commanditemmodel.cpp
Previously, with desktop entries, their real file names were used for sorting by default.
Closes https://github.com/lxqt/lxqt-runner/issues/194
NOTE: You could use "libreoffice" for testing, although there are many other ways too. Since the visible name is the last criterion, this is only about desktop entries that may appear in lxqt-panel's main menu.
> Use visible names as the last criterion for sorting items

- dialog.cpp
We need to write the width to the config file only when the resize event is "spontaneous", as Qt calls it.
Closes https://github.com/lxqt/lxqt-runner/issues/205
> No redundant writing of dialog width to config file

- dialog.cpp
- dialog.h
For some reason the dialog get repositioned by "outer world" (VM?) to
wrong position (0,0). The root cause of this move is yet unknown and
this is a workaround to avoid wrong position of the window.
closes #220
> dialog: Force correct position after move from outside of application

- configuredialog/configuredialog.cpp
- configuredialog/configuredialog.ui
- dialog.cpp
- dialog.h
LXQt Runner does that without an option. This patch adds an option, keeping the current behavior by default.
Use case: one may use LXQt Runner for running a specific app frequently, while using Main Menu for other apps.
> Added an option for clearing command on running

- dialog.cpp
`Qt::FramelessWindowHint` is needed for making the window frameless under most Wayland compositors.
> Made the window frameless explicitly

- CMakeLists.txt
- commanditemmodel.cpp
- dialog.cpp
- main.cpp
- providers.cpp
- providers.h
- widgets.cpp
- yamlparser.cpp
- yamlparser.h
Porting to Qt6 and using layer-shell-qt are dome simultaneously to make lxqt-runner completely ready for Wayland.
> Ported to Qt6 and used layer-shell-qt

- dialog.cpp
We have set scope in all (`lxqt-leave` has "window" afaik) layershell applications:
```
$ hyprctl layers
Monitor eDP-1:
Layer level 0 (background):
Layer 649ee26d0d20: xywh: 0 0 1920 1080, namespace: desktop
Layer level 1 (bottom):
Layer level 2 (top):
Layer 649ee264de10: xywh: 0 0 1920 48, namespace: dock
Layer 649ee14f4600: xywh: 1877 235 43 658, namespace: dock
Layer 649ee23d0f20: xywh: 161 1037 1555 43, namespace: dock
Layer 649ee125faf0: xywh: 688.5 267 500 46, namespace: launcher
Layer level 3 (overlay):
Layer 649ee2876ff0: xywh: 1341 50 534 89, namespace: notification
```
It makes it possible to add layer rules in compositor which support them, for example 
```
layerrule = noanim, launcher
layerrule = dimaround, launcher
```
> Added scope=launcher

- dialog.cpp
- providers.cpp
Previously when entering math and other expressions that were not valid QRegularExpression's, lxqt-runner would spam hundreds of Qt warnings that could be seen from the command line or journalctl.
> Suppress Qt warnings for invalid QRegularExpression

- configuredialog/configuredialog.cpp
- configuredialog/configuredialog.ui
- dialog.cpp
- dialog.h
… because window resizing is erratic with Wayland anchors (actually, it should have been disabled in the direction of anchors).
The compositor may change the mouse cursor to the resizing cursor, but the patch prevents resizing (even if it was resized, its configured size would be restored the next time it was shown).
X11 is kept intact.
Closes https://github.com/lxqt/lxqt-runner/issues/287
> Set the width by percentage on Wayland (in config dialog)

- dialog.cpp
- main.cpp
There is a detailed comment in the code, but in short,
* There is no Qt way for knowing the Wayland screen with the cursor. As a result, the size and vertical position of lxqt-runner (in case it's supposed to be centered vertically) are calculated and correct only relative to the smallest screen (which is usually the one with the largest scale factor). This means that the widget is wider than expected and above the center of another screen.
* Also, https://github.com/lxqt/lxqt-runner/commit/b0cad7975f5806bcd238f2d4285b5998a9857fb7 is reversed because, at least on KWin, the screen of lxqt-runner doesn't change without a hidden parent — don't ask me why, but perhaps the X11 developers encountered a similar issue.
NOTE: So far, this compromise is the only way — until Qt provides better …
> Best positioning of lxqt-runner with multi-screen Wayland

- dialog.cpp
But kept their jobs inside the list if Ctrl is also pressed, e.g., Ctrl+END selects the last entry.
The reason is that most users expect HOME/END to work inside the text entry, especially when SHIFT is also pressed.
Closes https://github.com/lxqt/lxqt-runner/issues/237
> Made HOME and END keys work inside the text entry

- dialog.cpp
Although we're either on X11 or on Wayland and this change makes no difference in practice, logically it's better to be explicit about X11 in one case, where slots are connected and disconnected.
> Be more explicit about X11
